#!/bin/bash
# usage:
# sudo ./trace_spi_startup

check_root()
{
    if [ $(id -u) != 0 ]; then
        echo "ERROR: please run this script as root (running 'sudo $(basename $0)' should work)" >&2
        exit 1
    fi
}

check_root

dmesg -C > /dev/null

echo "Loading wfx SPI driver..." > /dev/kmsg

echo spi0.0 > /sys/bus/spi/drivers/wfx-spi/unbind

echo "Enabling traces..." > /dev/kmsg
echo 1 > /sys/kernel/debug/tracing/events/wfx/hif_recv/enable
echo 1 > /sys/kernel/debug/tracing/events/wfx/hif_send/enable
echo 1 > /sys/kernel/debug/tracing/events/wfx/io_read/enable
echo 1 > /sys/kernel/debug/tracing/events/wfx/io_write/enable
echo 1 > /sys/kernel/debug/tracing/events/wfx/io_read32/enable
echo 1 > /sys/kernel/debug/tracing/events/wfx/io_write32/enable

echo spi0.0 > /sys/bus/spi/drivers/wfx-spi/bind

cat /sys/kernel/debug/tracing/trace_pipe &

# Write the UTC time to traces to allow aligning traces
date --rfc-3339=ns > /sys/kernel/debug/tracing/trace_marker
date --rfc-3339=ns > /dev/kmsg

sleep 10

echo "Disabling traces..." > /dev/kmsg
echo 0 > /sys/kernel/debug/tracing/events/wfx/hif_recv/enable
echo 0 > /sys/kernel/debug/tracing/events/wfx/hif_send/enable
echo 0 > /sys/kernel/debug/tracing/events/wfx/io_read/enable
echo 0 > /sys/kernel/debug/tracing/events/wfx/io_write/enable
echo 0 > /sys/kernel/debug/tracing/events/wfx/io_read32/enable
echo 0 > /sys/kernel/debug/tracing/events/wfx/io_write32/enable

# Write the UTC time at the end
date --rfc-3339=ns > /sys/kernel/debug/tracing/trace_marker
date --rfc-3339=ns > /dev/kmsg

exit 0
