#!/bin/bash

. wfx_set_variables

if [ -z ${1} ];
then
	echo "No WFX driver selected, listing possible drivers..."
	echo "You can proceed with:"
	echo "   wfx_driver_compile <driver>; wfx_use_driver <driver> for any of the following versions:"
	wfx_driver_sources
	echo "or:"
	echo "   wfx_use_driver <version> for any of the following versions:"
	wfx_drivers
	exit 0
else
	DRV=${1}
fi

KOS=${STORED_DRIVERS_PATH}/${kernel}/${DRV}

if [ -f ${STORED_DRIVERS_PATH}/${kernel}/${DRV}/wfx.ko ]
then
	MODULE="wfx.ko"
else
	if [ -f ${STORED_DRIVERS_PATH}/${kernel}/${DRV}/wfx_core.ko ]
	then
		MODULE="wfx_core.ko"
	else
		MODULE=""
	fi
fi

echo "DRV '${DRV}'"
echo "MODULE '${MODULE}'"

if [ -d ${KOS} ];
then
	if [ -z MODULE ];
	then
		echo "${KOS} directory exists, but doesn't contain WFX modules (.ko)!"
		echo "  Please check the content of this directory before proceeding!"
		echo "  You may need to use"
		echo "    wfx_compile_driver <path>"
		echo "  to compile the driver first"
	else
		# get rid of 'old style' driver folders to use 'extra' instead
		${SUDO} rm -fr /lib/modules/${kernel}/kernel/drivers/net/wireless/siliconlabs
		${SUDO} rm -fr /lib/modules/${kernel}/extra
		${SUDO} ln -s -f ${KOS}   /lib/modules/${kernel}/extra
		echo "updating modules dependencies..."
		${SUDO} depmod -a | grep wfx
		echo "updating modules dependencies done"
		${SUDO} modinfo wfx_core
	fi
else
	echo "${KOS} directory doesn't exist! Please use one of the following values:"
	wfx_drivers
fi

drv_ln=$(realpath /lib/modules/${kernel}/extra)
printf "\nWFX driver folder /lib/modules/${kernel}/extra -> ${drv_ln}\n"
ls -al ${drv_ln}/*.ko
