#!/bin/sh
# wfx_station_start [configuration_file]
# Start station with configuration file from command line, otherwise use /etc/wpa_supplicant/wpa_supplicant.conf

. wfx_set_env
check_root
WFX_MODE=$(wfx_mode)

if [ "${WFX_MODE}" = "ap" ];
then
        echo  "ERROR: Currently in ap mode! Use 'wfx_ap_stop' before starting station mode"
        exit 0
fi

if [ "${WFX_MODE}" = "conflict" ];
then
        echo  "ERROR: Currently in conflict! Use 'wfx_ap_stop' and 'wfx_station_stop' before starting station mode"
        exit 0
fi

if [ -z ${1} ]; then
        WPA_CONF="/etc/wpa_supplicant/wpa_supplicant.conf"
else
        if [ -f "${1}" ];
        then
                WPA_CONF=${1}
        else
                echo "ERROR: unknown ${1} configuration file"
                exit 0
        fi
fi

if [ -d /var/run/wpa_supplicant ]; then
    echo "wpa_supplicant already launched, terminating"
    set -ex
    /sbin/wpa_cli terminate
    sleep 0.5
    set +ex
fi

set -ex
wpa_supplicant -B -i wlan0 -c  ${WPA_CONF}
set +ex

exit 0
