#!/bin/bash

. wfx_set_env
check_root
check_rpi

if [ $# -lt 1 ]; then
    echo "Expecting at least one argument" >&2
    exit 1
fi

for f in "$@"; do
    INFILE=$f
    INFILE_BASE=$(basename $INFILE)
    OUTFILE_BASE=${INFILE_BASE%-overlay.dts}.dtbo
    OUTFILE=/boot/overlays/$OUTFILE_BASE

    if [ "$INFILE_BASE" = "$OUTFILE_BASE" ]; then
        echo "Input file is expected to end with '-overlay.dts'" >&2
        exit 1
    fi

    set -ex
    dtc -@ -W no-unit_address_vs_reg $INFILE -o $OUTFILE
    set +ex
done
