#!/bin/bash

. wfx_set_variables

${SUDO} modprobe -v wfx -r

if [ ${model} == "Pi" ]; then
	echo 3f300000.mmc | sudo tee /sys/bus/platform/drivers/mmc-bcm2835/unbind
fi

if [ "${1}" == "clear" ]; then
	${SUDO} dmesg -C
fi

if [ ${model} == "Pi" ]; then
	echo 3f300000.mmc | sudo tee /sys/bus/platform/drivers/mmc-bcm2835/bind
fi

${SUDO} modprobe -v wfx
