#!/bin/bash
# Copyright (c) 2018, Silicon Laboratories
# See COPYING for license.

. wfx_set_env
check_root

echo "Start   configuration:"
. wfx_config 0
echo ""

wfx_enable_sdio_overlay
wfx_disable_spi_overlay

wfx_blacklist_driver brcmfmac
wfx_blacklist_driver wfx -

echo "Final configuration:"
. wfx_config 1 0

echo ""

if [ -n "$config_message" ]; then
	echo "Make sure you set the switch in the 'SDIO' position,"
	echo "${config_message}, then"
	echo "the WFx200 SDIO driver will be loaded automatically at boot"
else
	if [ -n "$startup_message" ]; then
		echo "${startup_message}"
		echo "you can now use 'sudo wfx_sdio_reload' to load the WFx200 driver."
		echo "the WFx200 SDIO driver will be loaded automatically at boot"
	fi
fi
