#!/bin/bash

. wfx_colors

if [ -e "$1" ];
then
	FILES=$( ls $1 )
	for f in ${FILES}
	do
		printf "   %s\n" $(realpath $f)
	done
else
	if [ "${2}" == "critical" ]
	then
		printf "   %-40s ${RED}MISSING_CRITICAL_FILE${NO}\n" "$1"
	else
		printf "   %-40s ${INV}NO_SUCH_FILE${NO}\n" "$1"
	fi
fi
