#!/bin/bash

. wfx_set_env
check_root
check_pi

. wfx_colors

tiny_cat()
{
    if [ -e "$1" ]; then
        printf "───────────────────  %-40s\n" "$(realpath $1)"
        grep -v -e '^#' -e '^$' $1
    else
        printf "───────────────────  %-40s ${INV}NO_SUCH_FILE${NO}\n" "$1"
    fi
}

tiny_cat /boot/cmdline.txt
tiny_cat /boot/config.txt
tiny_cat /etc/modprobe.d/raspi-blacklist.conf

tiny_cat /etc/hostname
tiny_cat /etc/hosts
tiny_cat /etc/rc.local

tiny_cat /etc/dnsmasq.conf
tiny_cat /etc/dhcpcd.conf

tiny_cat /etc/modules
tiny_cat /etc/modprobe.d/wfx.conf

tiny_cat /etc/network/interfaces

tiny_cat /etc/wpa_supplicant/wpa_supplicant.conf

tiny_cat /etc/hostapd/hostapd.conf

