#!/bin/bash

. wfx_set_env
check_rpi

OVERLAY=$(cat /boot/config.txt | grep ^dtoverlay=wfx-)
case "$OVERLAY" in
    *spi*)
        echo spi
        ;;
    *sdio*)
        echo sdio
        ;;
    *)
        echo "Cannot find dtoverlay in /boot/config.txt" >&2
        exit 1
        ;;
esac
