#!/bin/bash
# Copyright (c) 2018, Silicon Laboratories
# See license terms contained in COPYING file

. wfx_set_env
check_root

case "$(wfx_bus)" in
    spi)
        wfx_spi_reload "$@"
        ;;
    sdio)
        wfx_sdio_reload "$@"
        ;;
    *)
        exit 1
        ;;
esac
