#!/bin/bash
# Copyright (c) 2018, Silicon Laboratories
# See license terms contained in COPYING file

VERSION=$1

# Launch install for a specific version
git show $VERSION:linux_scripts/low_level/tools_install.sh | bash -s $VERSION
