#!/bin/bash
# Copyright (c) 2018, Silicon Laboratories
# See license terms contained in COPYING file

. wfx_set_env
check_no_root

OPTIONS="--all --tags --prune"

git -C $GITHUB_DRIVER_PATH fetch $OPTIONS --recurse-submodules
git -C $GITHUB_FIRMWARE_PATH fetch $OPTIONS
git -C $GITHUB_TOOLS_PATH fetch $OPTIONS
git -C $GITHUB_TOOLS_INTERNAL_PATH fetch $OPTIONS || true
