#!/bin/bash
# Copyright (c) 2018, Silicon Laboratories
# See license terms contained in COPYING file

set -e

. wfx_set_env
check_rpi
check_root

OVERLAY=$(cat /boot/config.txt | grep "^dtoverlay=wfx-")
case "$OVERLAY" in
    *spi*sdio*|*sdio*spi*)
        echo "ERROR: SPI and SDIO overlays and both enabled in /boot/config.txt" >&2
        exit 1
        ;;
    *spi*)
        echo spi
        ;;
    *sdio*)
        echo sdio
        ;;
    *)
        echo "ERROR: cannot find dtoverlay entry in /boot/config.txt" >&2
        exit 1
        ;;
esac
