#!/bin/bash
# Copyright (c) 2018, Silicon Laboratories
# See license terms contained in COPYING file

. wfx_set_env
check_rpi
check_hat

for f in /proc/device-tree/hat/*; do
    printf "%-20s %s\n" "$(basename $f)" "$(cat $f)"
done
