#!/bin/bash
# Copyright (c) 2018, Silicon Laboratories
# See license terms contained in COPYING file

. wfx_set_env
check_rpi
check_hat

get_letter()
{
    local hex=$(printf "%x" $(( $1+0x41 )) )
    printf "\x$hex"
}

vendor=$(cat /proc/device-tree/hat/vendor | tr -d '\0')
product=$(cat /proc/device-tree/hat/product | tr -d '\0')
product_id=$(cat /proc/device-tree/hat/product_id | tr -d '\0')
product_ver=$(cat /proc/device-tree/hat/product_ver | tr -d '\0')
uuid=$(cat /proc/device-tree/hat/uuid | tr -d '\0')

variant_val=$((($product_ver >> 12) & 0x0F))
  major_val=$((($product_ver >>  8) & 0x0F))
  minor_val=$((($product_ver >>  0) & 0xFF))

board_id=$(($product_id))
variant=$(get_letter $variant_val)
major=$(get_letter $major_val)
minor=$(printf "%02d" $minor_val)

if [[ "$1" == "-v" ]]; then
    printf "%20s %20s " $vendor $product
fi
echo "BRD${board_id}${variant}_Rev_${major}${minor}"
