#!/bin/sh
# retrieves the AP’s SSID (if no argument), otherwise sets it to ‘ssid’
# NB: only works for the default hostapd configuration file if not currently in AP mode!
#     To configure dedicated hostapd files, it is recommended to edit them

. wfx_set_env
check_root

WFX_MODE=$(wfx_mode)

if [ ! $# -eq 0 ];
then
	AP_SSID="${1}"
	sed -i~ 's/ssid=.*$/ssid='${AP_SSID}'/m' /etc/hostapd/hostapd.conf
else
	if [ "${WFX_MODE}" = "ap" ];
	then
		AP_SSID=$(hostapd_cli status | grep ^ssid | cut -d "=" -f 2)
	else
		AP_SSID=$(cat /etc/hostapd/hostapd.conf | grep ^ssid | cut -d "=" -f 2)
	fi
fi

echo "$AP_SSID"
