#!/bin/bash
# Copyright (c) 2018, Silicon Laboratories
# See license terms contained in COPYING file

. wfx_set_env
check_no_root

if [ ! -d "$GITHUB_DRIVER_PATH" ]; then
    echo "error: cannot find directory $GITHUB_DRIVER_PATH" >&2
    exit 1
fi

if [ $# -gt 0 ]; then
    if ! git -C $GITHUB_DRIVER_PATH checkout $1; then
        echo "error: cannot get tag $1" >&2
        echo "Possible tags:"
        git -C $GITHUB_DRIVER_PATH tag | sed 's/^/  /'
        exit 1
    fi
fi

DRIVER_VER=$(git -C $GITHUB_DRIVER_PATH describe --tags --dirty)
KERNEL_VER=$(uname -r)

printf "Installing driver %s for kernel %s\n" "$DRIVER_VER" "$KERNEL_VER"
set -ex
make -C $GITHUB_DRIVER_PATH -j 5
sudo make -C $GITHUB_DRIVER_PATH install
sudo depmod -w
