#!/bin/bash
# Copyright (c) 2018, Silicon Laboratories
# See license terms contained in COPYING file

. wfx_set_env
check_root

echo "Start   configuration:"
. wfx_config 0
echo ""

wfx_disable_sdio_overlay
wfx_enable_spi_overlay

wfx_blacklist_driver brcmfmac
wfx_blacklist_driver wfx

echo "Final configuration:"
. wfx_config 1 0

echo ""

if [ -n "$config_message" ]; then
	echo "Make sure you set the switch in the 'SPI' position,"
	echo "${config_message}, then"
	echo "use 'sudo wfx_driver_reload' to load the WFx200 driver"
else
	if [ -n "$startup_message" ]; then
		echo "${startup_message}"
		echo "you will need to use 'sudo wfx_driver_reload' to load the WFx200 driver"
	fi
fi
