#!/bin/bash

. wfx_set_env
check_no_root

if [ ! -d "$GITHUB_DRIVER_PATH/wfx" ]; then
    echo "Cannot find directory $GITHUB_DRIVER_PATH/wfx" >&2
    exit 1
fi

if [ $# -gt 0 ]; then
    if ! git -C $GITHUB_DRIVER_PATH checkout $1; then
        echo "Cannot get tag $1" >&2
        echo "Possible tags:"
        git -C $GITHUB_DRIVER_PATH tag | sed 's/^/  /'
        exit 1
    fi
fi

DRIVER_VER=$(git -C $GITHUB_DRIVER_PATH describe --tags --dirty)
KERNEL_VER=$(uname -r)

printf "Installing driver %s for kernel %s\n" "$DRIVER_VER" "$KERNEL_VER"
set -ex
make -C $GITHUB_DRIVER_PATH/wfx
sudo make -C $GITHUB_DRIVER_PATH/wfx install
sudo depmod -w
