#!/bin/bash
# Copyright (c) 2018, Silicon Laboratories
# See COPYING for license.

. wfx_set_env
check_root

if [ "$#" != 1 ]; then
    echo "Wrong number of arguments. One compressed or plain PDS is expected." >&2
    exit 1
fi

INFILE=$1
if ! [ -f "$INFILE" ]; then
    echo "$INFILE not found" >&2
    exit 1
fi

set -ex
pds_compress $INFILE /sys/kernel/debug/ieee80211/phy*/wfx/send_pds
