#!/bin/bash

. wfx_pds quiet
. wfx_board quiet

GIT_PDS_FILES=""
STORED_PDS=""

if [ -d "${GIT_PDS_DIR}" ];
then
	GIT_PDS_FILES=$( ls -v ${GIT_PDS_DIR} | grep ${PDS_GREP} )
fi

if [ -d "${STORED_PDS_PATH}" ];
then
	STORED_PDSS=$(ls -v ${STORED_PDS_PATH} | grep ${PDS_GREP} )
fi

if [ "${1}" != "quiet" ];
then
	if [ "${STORED_PDSS}" != "" ];
	then
		echo "PDSs available from ${STORED_PDS_PATH} local copies"
		for pds in ${STORED_PDSS}
		do
			if [ "${BOARD}" != "" ];
			then
				test=$(echo ${pds} | grep "${BOARD}")
			fi
			if [ "$test" != "" ]; then
				printf "  ${LGREEN}${pds}${NO}  (matching board info)\n"
			else
				printf "  ${pds}\n"
			fi
		done
	fi
	if [ "${GIT_PDS_FILES}" != "" ];
	then
		echo "PDSs available from 'wfx_firmware' GIT clone (there may be more available if you pull from Github)"
		for pds in ${GIT_PDS_FILES}
		do
			if [ "${BOARD}" != "" ];
			then
				test=$(echo ${pds} | grep "${BOARD}")
			fi
			test=$(echo ${pds} | grep "${BOARD}")
			if [ "$test" != "" ]; then
				printf "  ${LGREEN}${pds}${NO}  (matching board info) test '$test' BOARD '$BOARD'\n"
			else
				printf "  ${pds}\n"
			fi
		done
	fi
fi
