#!/bin/bash
# Copyright (c) 2018, Silicon Laboratories
# See license terms contained in COPYING file

set -e

. wfx_set_env
check_rpi
check_root

MODE=$1

case "$MODE" in
    spi)
        sed -i~ -re 's/^(dtoverlay=wfx-sdio)/#\1/m' /boot/config.txt
        sed -i -re 's/^#(dtoverlay=wfx-spi)/\1/m' /boot/config.txt
        ;;
    sdio)
        sed -i~ -re 's/^(dtoverlay=wfx-spi)/#\1/m' /boot/config.txt
        sed -i -re 's/^#(dtoverlay=wfx-sdio)/\1/m' /boot/config.txt
        ;;
    *)
        echo "ERROR: unsupported bus mode: $MODE" >&2
        exit 1
        ;;
esac
