#!/bin/bash
# Copyright (c) 2018, Silicon Laboratories
# See license terms contained in COPYING file

. wfx_set_env
check_not_root

set -e

USAGE="Usage: $(basename $0) OPTION

Install driver

Otpions:
  --help         display this message
  --current      install the driver from current sources state
  --tag <tag>    install the driver specified by tag
"

GIT="git -C $GITHUB_DRIVER_PATH"

case "$1" in
    --help)
        echo "$USAGE"
        exit 0
        ;;
    --current)
        ;;
    --tag)
        TAG=$2
        check_working_clean $GITHUB_DRIVER_PATH
        if ! $GIT checkout --quiet $TAG; then
            echo "ERROR: cannot get tag $TAG" >&2
            echo "Possible tags:" >&2
            $GIT tag | sed 's/^/  /' >&2
            exit 1
        fi
        ;;
    *)
        echo "ERROR: unknown command $1" >&2
        echo "$USAGE" >&2
        exit 1
        ;;
esac

printf "Installing driver %s for kernel %s\n" "$($GIT describe --tags --dirty)" "$(uname -r)"

set -x

$GIT submodule update --init
make -C $GITHUB_DRIVER_PATH ${KDIR:+KDIR=$KDIR} -j 5
sudo make -C $GITHUB_DRIVER_PATH ${KDIR:+KDIR=$KDIR} modules_install

# depmod needs to work within a chroot too
if [ -z "$KDIR" ]; then
    DEPMOD_VER=''
else
    DEPMOD_VER="$(cat $KDIR/include/config/kernel.release)"
fi
sudo depmod $DEPMOD_VER

echo "Success"
