#!/bin/bash
# Copyright (c) 2018, Silicon Laboratories
# See license terms contained in COPYING file

. wfx_set_env
check_no_root

set -e

if [ ! -d "$GITHUB_DRIVER_PATH" ]; then
    echo "ERROR: cannot find directory $GITHUB_DRIVER_PATH" >&2
    exit 1
fi

if [ $# -gt 0 ]; then
    check_working_clean $GITHUB_DRIVER_PATH

    if ! git -C $GITHUB_DRIVER_PATH checkout --quiet $1; then
        echo "ERROR: cannot get tag $1" >&2
        echo "Possible tags:"
        git -C $GITHUB_DRIVER_PATH tag | sed 's/^/  /'
        exit 1
    fi
fi

DRIVER_VER=$(git -C $GITHUB_DRIVER_PATH describe --tags --dirty)
KERNEL_VER=$(uname -r)

printf "Installing driver %s for kernel %s\n" "$DRIVER_VER" "$KERNEL_VER"
set -x
git -C $GITHUB_DRIVER_PATH submodule update --init
make -C $GITHUB_DRIVER_PATH ${KDIR:+KDIR=$KDIR} -j 5
sudo make -C $GITHUB_DRIVER_PATH ${KDIR:+KDIR=$KDIR} modules_install

# depmod needs to work within a chroot too
if [ -z "$KDIR" ]; then
    DEPMOD_VER=''
else
    DEPMOD_VER="$(cat $KDIR/include/config/kernel.release)"
fi
sudo depmod $DEPMOD_VER

echo "Success"
