#!/bin/bash
# usage:
# sudo ./trace_sdio_startup

check_root()
{
    if [ $(id -u) != 0 ]; then
        echo "ERROR: please run this script as root (running 'sudo $(basename $0)' should work)" >&2
        exit 1
    fi
}

check_root

dmesg -C > /dev/null

echo "Loading wfx SDIO driver..." > /dev/kmsg

if ! echo 3f300000.mmc > /sys/bus/platform/drivers/mmc-bcm2835/unbind 2>/dev/null; then # Raspberry mmc driver with rpi-3
    if ! echo fe300000.mmc > /sys/bus/platform/drivers/mmc-bcm2835/unbind 2>/dev/null; then # Raspberry mmc driver with rpi-4
        echo 3f300000.sdhci > /sys/bus/platform/drivers/sdhci-iproc/unbind 2>/dev/null # Mainstream driver
    fi
fi

echo "Enabling traces..." > /dev/kmsg
echo ' name == "mmc1" && cmd_opcode < 53 ' > /sys/kernel/debug/tracing/events/mmc/mmc_request_start/filter
echo ' name == "mmc1" && cmd_opcode < 53 ' > /sys/kernel/debug/tracing/events/mmc/mmc_request_done/filter

echo 1 > /sys/kernel/debug/tracing/events/mmc/mmc_request_start/enable
echo 1 > /sys/kernel/debug/tracing/events/mmc/mmc_request_done/enable
echo 1 > /sys/kernel/debug/tracing/events/wfx/hif_recv/enable
echo 1 > /sys/kernel/debug/tracing/events/wfx/hif_send/enable
echo 1 > /sys/kernel/debug/tracing/events/wfx/piggyback/enable
echo 1 > /sys/kernel/debug/tracing/events/wfx/io_read/enable
echo 1 > /sys/kernel/debug/tracing/events/wfx/io_write/enable
echo 1 > /sys/kernel/debug/tracing/events/wfx/io_read32/enable
echo 1 > /sys/kernel/debug/tracing/events/wfx/io_write32/enable

if ! echo 3f300000.mmc > /sys/bus/platform/drivers/mmc-bcm2835/bind 2>/dev/null; then # Raspberry mmc driver with rpi-3
    if ! echo fe300000.mmc > /sys/bus/platform/drivers/mmc-bcm2835/bind 2>/dev/null; then # Raspberry mmc driver with rpi-4
        echo 3f300000.sdhci > /sys/bus/platform/drivers/sdhci-iproc/bind 2>/dev/null # Mainstream driver
    fi
fi

# Write the UTC time to traces to allow aligning traces
date --rfc-3339=ns > /sys/kernel/debug/tracing/trace_marker
date --rfc-3339=ns > /dev/kmsg

sleep 10

echo "Disabling traces..." > /dev/kmsg
echo 0 > /sys/kernel/debug/tracing/events/mmc/mmc_request_start/enable
echo 0 > /sys/kernel/debug/tracing/events/mmc/mmc_request_done/enable
echo 0 > /sys/kernel/debug/tracing/events/wfx/hif_recv/enable
echo 0 > /sys/kernel/debug/tracing/events/wfx/hif_send/enable
echo 0 > /sys/kernel/debug/tracing/events/wfx/piggyback/enable
echo 0 > /sys/kernel/debug/tracing/events/wfx/io_read/enable
echo 0 > /sys/kernel/debug/tracing/events/wfx/io_write/enable
echo 0 > /sys/kernel/debug/tracing/events/wfx/io_read32/enable
echo 0 > /sys/kernel/debug/tracing/events/wfx/io_write32/enable

# Write the UTC time at the end
date --rfc-3339=ns > /sys/kernel/debug/tracing/trace_marker
date --rfc-3339=ns > /dev/kmsg

exit 0
