#!/bin/bash
# Copyright (c) 2018, Silicon Laboratories
# See license terms contained in COPYING file

set -e
. wfx_set_env
check_rpi

USAGE="Usage: $(basename $0) OPTION

Show or set bus mode (SPI or SDIO)

Options:
  --help         display this message
  --show         show bus mode
  --set sdio|spi set bus mode
"

main()
{
    case "$1" in
        --help)
            echo "$USAGE"
            exit 0
            ;;
        --show)
            bus_show
            ;;
        --set)
            bus_set $2
            ;;
        *)
            echo "ERROR: unknown command $1" >&2
            echo "$USAGE" >&2
            exit 1
            ;;
    esac
}

bus_show()
{
    OVERLAY=$(cat /boot/config.txt | grep "^dtoverlay=wfx-")
    case "$OVERLAY" in
        *spi*sdio*|*sdio*spi*)
            echo "ERROR: SPI and SDIO overlays and both enabled in /boot/config.txt" >&2
            exit 1
            ;;
        *spi*)
            echo spi
            ;;
        *sdio*)
            echo sdio
            ;;
        *)
            echo "ERROR: cannot find dtoverlay entry in /boot/config.txt" >&2
            exit 1
            ;;
    esac
}

bus_set()
{
    MODE=$1
    check_root
    case "$MODE" in
        spi)
            sed -i~ -re 's/^(dtoverlay=wfx-sdio)/#\1/m' /boot/config.txt
            sed -i -re 's/^#(dtoverlay=wfx-spi)/\1/m' /boot/config.txt
            ;;
        sdio)
            sed -i~ -re 's/^(dtoverlay=wfx-spi)/#\1/m' /boot/config.txt
            sed -i -re 's/^#(dtoverlay=wfx-sdio)/\1/m' /boot/config.txt
            ;;
        *)
            echo "ERROR: unsupported bus mode: $MODE" >&2
            exit 1
            ;;
    esac
    echo "WARNING: reboot the board for the bus change to take effect (sudo reboot)"
}

main $@
