#!/bin/bash
# Copyright (c) 2018, Silicon Laboratories
# See license terms contained in COPYING file

. wfx_set_env
run_as_root

set -o pipefail

print_command()
{
    TEXT=$1
    shift
    RESULT=$(eval $@ 2>/dev/null) || RESULT="not found"
    printf "%-30s%s\n" "$TEXT:" "$RESULT"
}

print_command "Driver installed file" "modinfo -n wfx"
print_command "Driver installed version" "modinfo -F version wfx"
print_command "Driver loaded version" "cat /sys/module/wfx/version"

printf "\n"

print_command "Firmware loaded version" "sed -nre 's/Firmware:.* WFM(.*)/\1/p' /sys/kernel/debug/ieee80211/phy*/wfx/status | xargs | tr ' ' ."
print_command "Firmware loaded label" "sed -nre \"s/FW label:.*'(.*)'/\1/p\" /sys/kernel/debug/ieee80211/phy*/wfx/status"

# TODO: use status file once keyset is available
print_command "Firmware loaded keyset" "dmesg | grep 'wfx.*Firmware' | tail -1 | sed -nre \"s/.*Keyset: (..).*/\1/p\""

printf "\n"

print_command "PDS file" "realpath -e /lib/firmware/wf200.pds"
print_command "PDS API version" "pds_compress /lib/firmware/wf200.pds | sed -ne 's/^{a:{a:\(.\),b:\(.\).*/\1.\2/p'"
