#!/bin/bash
# Copyright (c) 2018, Silicon Laboratories
# See license terms contained in COPYING file

. wfx_set_env
run_as_root

set -e

USAGE="Usage: $(basename $0) OPTION

Install PDS

Run wfx_firmware_install before running this command to make sure
PDS version is aligned with firmware version.

Otpions:
  --help          display this message
  --list          list supported EXP boards
  --auto          auto-detect EXP board
  --board MODEL   select EXP board MODEL
  --custom FILE   select custom .pds.in FILE
"

GIT="git -C $GITHUB_FIRMWARE_PATH"

case "$1" in
    --help)
        echo "$USAGE"
        exit 0
        ;;
    --list)
        (cd $GITHUB_PDS_PATH; ls -1 *.pds.in | sed 's/\.pds\.in//')
        exit 0
        ;;
    --auto)
        BOARD="$(wfx_info --board)"
        INFILE="$GITHUB_PDS_PATH/$BOARD.pds.in"
        ;;
    --board)
        INFILE="$GITHUB_PDS_PATH/$2"
        INFILE="${INFILE%.pds.in}.pds.in"
        ;;
    --custom)
        INFILE="$2"
        ;;
    *)
        echo "ERROR: unknown command $1" >&2
        echo "$USAGE" >&2
        exit 1
        ;;
esac

if [ ! -e "$INFILE" ]; then
    echo "ERROR: cannot find PDS $INFILE" >&2
    exit 1
fi

INFILE_BASE=$(basename $INFILE)
OUTFILE_BASE=${INFILE_BASE%.in}
OUTFILE=/lib/firmware/$OUTFILE_BASE

printf "Installing PDS %s\n" "$INFILE"
set -x
pds_compress $INFILE $OUTFILE
ln -sfn $OUTFILE_BASE /lib/firmware/wf200.pds
echo "Success"
