#!/bin/bash
# Copyright (c) 2018, Silicon Laboratories
# See license terms contained in COPYING file

set -e
. wfx_set_env
check_root

DEFAULT_CHIP_KEY=C0

USAGE="Usage: $(basename $0) OPTION

Install firmware

Otpions:
  --help         display this message
  --tag <tag>    install the firmware specified by tag
"

GIT="git -C $GITHUB_FIRMWARE_PATH"

case "$1" in
    --help)
        echo "$USAGE"
        exit 0
        ;;
    --current)
        ;;
    --tag)
        TAG=$2
        [ -z "$TAG" ] && echo "$USAGE" >&2 && exit 1
        check_working_clean $GITHUB_FIRMWARE_PATH
        if ! $GIT checkout --quiet $TAG; then
            echo "ERROR: cannot get tag $TAG" >&2
            exit 1
        fi
        ;;
    *)
        echo "ERROR: unknown command $1" >&2
        echo "$USAGE" >&2
        exit 1
        ;;
esac

FIRMWARE_VER=$($GIT describe --tags --dirty)

printf "Installing firmware %s\n" "$FIRMWARE_VER"
for i in $GITHUB_FIRMWARE_PATH/wfm_wf200_??.sec; do
    INFILE=$i
    INFILE_BASE=$(basename $INFILE)
    OUTFILE_BASE=${INFILE_BASE%.sec}-$FIRMWARE_VER.sec
    OUTFILE=/lib/firmware/$OUTFILE_BASE
    set -x
    cp $INFILE $OUTFILE
    ln -sfn $OUTFILE_BASE /lib/firmware/$INFILE_BASE
    { set +x; } 2>/dev/null # Disable traces without disturbing user
done

set -x
ln -sfn wfm_wf200_$DEFAULT_CHIP_KEY.sec /lib/firmware/wfm_wf200.sec
echo "Success"
