#!/bin/bash
# Copyright (c) 2018, Silicon Laboratories
# See license terms contained in COPYING file

. wfx_set_env
check_not_root

set -e

USAGE="Usage: $(basename $0) OPTION

Build and install driver

Otpions:
  --help         display this message
  --current      install the driver from current sources state
  --version VER  install the driver specified by VER
  --list-tags    list driver versions
"

GIT="git -C $GITHUB_DRIVER_PATH"
WFX_GIT="$GITHUB_TOOLS_PATH/update/git.sh --path $GITHUB_DRIVER_PATH"

case "$1" in
    --help)
        echo "$USAGE"
        exit 0
        ;;
    --current)
        ;;
    --version)
        $WFX_GIT --version "$2"
        ;;
    --list-tags)
        $WFX_GIT --list
        exit 0
        ;;
    *)
        echo "ERROR: unknown command $1" >&2
        echo "$USAGE" >&2
        exit 1
        ;;
esac

# depmod needs to work within a chroot too
if [ -z "$KDIR" ]; then
    DEPMOD_VER=''
else
    DEPMOD_VER="$(cat $KDIR/include/config/kernel.release)"
fi

# Enable ccache if it is installed
export PATH=/usr/lib/ccache:$PATH

set -x
$GIT submodule update --init
make -C $GITHUB_DRIVER_PATH ${KDIR:+KDIR=$KDIR} -j 5
sudo make -C $GITHUB_DRIVER_PATH ${KDIR:+KDIR=$KDIR} modules_install
sudo depmod $DEPMOD_VER
set +x

echo
echo "Driver $($GIT describe --tags --dirty) installed, please reload (wfx_driver_reload)"
