#!/bin/bash
# Copyright (c) 2018, Silicon Laboratories
# See license terms contained in COPYING file

set -euo pipefail
. wfx_set_env
run_as_root

USAGE="Usage: $(basename $0) OPTION

Install PDS

Run wfx_firmware_install before running this command to make sure
PDS version is aligned with firmware version.

Otpions:
  --help          display this message
  --list-boards   list supported boards
  --auto          auto-detect board
  --board MODEL   select board MODEL
  --custom FILE   install custom .pds.in FILE

Examples:
-install current PDS with board auto-detection
$(basename $0) wfx_pds_install --auto

-install custom PDS
$(basename $0) wfx_pds_install --custom ~/my_test_PDS.pds.in
"

BOARD=""
INFILE=""
PDS_PATH="$GITHUB_PDS_PATH"

[ $# -eq 0 ] && error
LONGOPTS="help,list-boards,auto,board:,custom:,repo:"
! PARSED=$(getopt --options="" --longoptions=$LONGOPTS --name "$0" -- "$@")
[[ ${PIPESTATUS[0]} -ne 0 ]] && error
eval set -- "$PARSED"
while true; do
    case "$1" in
        --list-boards)
            tree $PDS_PATH -P '*.pds.in' -I definitions --noreport
            exit 0
            ;;
        --auto)
            BOARD="$(wfx_info --board)"
            INFILE="$PDS_PATH/$BOARD.pds.in"
            ;;
        --board)
            BOARD="${2%.pds.in}"; shift
            INFILE="$PDS_PATH/$BOARD.pds.in"
            ;;
        --custom)
            INFILE="$2"; shift
            ;;
        --repo)
            PDS_PATH="$2"; shift
            ;;
        --help)
            echo "$USAGE"; exit 0
            ;;
        --)
            shift; break
            ;;
        *)
            echo "ERROR: please use --auto, --board or --custom" >&2 ; error
            ;;
    esac
    shift
done
[ $# -ne 0 ] && error

[ -z "$BOARD" ] && [ -z "$INFILE" ] && error "please use --auto, --board or --custom"
[ ! -e "$INFILE" ] && error "cannot find PDS $INFILE, board $BOARD may not be supported"

INFILE_BASE=$(basename $INFILE)
OUTFILE_BASE=${INFILE_BASE%.pds.in}.pds
OUTFILE=/lib/firmware/$OUTFILE_BASE

sudo pds_compress $INFILE $OUTFILE --include "$PDS_PATH/definitions"
sudo ln -sfn $OUTFILE_BASE /lib/firmware/wf200.pds

if [ ! -z "$BOARD" ]; then
    echo "PDS installed for board $BOARD"
else
    echo "custom PDS $INFILE installed"
fi
