#!/bin/bash
# Copyright (c) 2018, Silicon Laboratories
# See license terms contained in COPYING file

set -e
. wfx_set_env
check_not_root

DEFAULT_CHIP_KEY=C0

USAGE="Usage: $(basename $0) OPTION

Install firmware

Otpions:
  --help         display this message
  --version VER  install the firmware specified by VER
  --list-tags    list firmware versions
"

GIT="git -C $GITHUB_FIRMWARE_PATH"
WFX_GIT="wfx_git --path $GITHUB_FIRMWARE_PATH"

case "$1" in
    --help)
        echo "$USAGE"
        exit 0
        ;;
    --version)
        VERSION="$2"
        $WFX_GIT --version "$VERSION"
        ;;
    --list-tags)
        $WFX_GIT --list
        exit 0
        ;;
    *)
        echo "ERROR: unknown command $1" >&2
        echo "$USAGE" >&2
        exit 1
        ;;
esac

FIRMWARE_VER=$($GIT describe --tags --dirty)

printf "Installing firmware %s\n" "$FIRMWARE_VER"
sudo rm -fv /lib/firmware/wfm_wf200.sec
sudo rm -fv /lib/firmware/wfm_wf200_[A-Z0-9][0-9].sec
sudo rm -fv /lib/firmware/wfm_wf200_[A-Z0-9][0-9]-FW[0-9].[0-9].[0-9].sec
for i in $GITHUB_FIRMWARE_PATH/wfm_wf200_??.sec; do
    INFILE=$i
    INFILE_BASE=$(basename $INFILE)
    OUTFILE_BASE=${INFILE_BASE%.sec}-$FIRMWARE_VER.sec
    OUTFILE=/lib/firmware/$OUTFILE_BASE
    set -x
    sudo cp $INFILE $OUTFILE
    sudo ln -sfn $OUTFILE_BASE /lib/firmware/$INFILE_BASE
    { set +x; } 2>/dev/null # Disable traces without disturbing user
done

set -x
echo "Firmware installed for version $VERSION"
