#!/bin/bash
# Copyright (c) 2018, Silicon Laboratories
# See license terms contained in COPYING file

. wfx_set_env
. wfx_colors

check_file()
{
    [ "$2" == "--critical" ] && CRIT=1
    [ "$1" == "--critical" ] && CRIT=1 && shift
    if [ -e "$1" ]; then
        printf "   %-40s OK\n" $(realpath $1)
    else
        if [ -z "$CRIT" ]; then
            printf "   %-40s ${INV}NO SUCH FILE${NO}\n" "$1"
        else
            printf "   %-40s ${RED}MISSING CRITICAL FILE${NO}\n" "$1"
        fi
    fi
}

model=$(cat /sys/firmware/devicetree/base/model | cut -d ' ' -f 2)
case $model in
    "Pi")
        check_file --critical /boot/cmdline.txt
        check_file --critical /boot/config.txt
        check_file --critical /boot/overlays/pi3-disable-bt.dtbo
        check_file --critical /boot/overlays/wfx-sdio.dtbo
        check_file --critical /boot/overlays/wfx-spi.dtbo
        check_file --critical /etc/modprobe.d/raspi-blacklist.conf
        ;;
    "i.MX6")
        check_file --critical /boot/uEnv.txt
        ;;
esac

check_file --critical /lib/firmware/wfm_wf200.sec
check_file --critical /lib/firmware/wf200.pds
check_file --critical /lib/modules/$(uname -r)/extra/wfx.ko

check_file /etc/modprobe.d/wfx.conf
check_file /etc/modules

check_file /etc/hostname
check_file /etc/hosts

check_file /etc/rc.local
check_file /etc/network/interfaces

check_file /etc/dhcpcd.conf
check_file $GITHUB_CONF_PATH/wpa_supplicant.conf
check_file $GITHUB_CONF_PATH/hostapd.conf
check_file $GITHUB_CONF_PATH/dnsmasq.conf
