#!/bin/bash
# Copyright (c) 2018, Silicon Laboratories
# See license terms contained in COPYING file
#
# Reload WFX driver
#

. wfx_set_env
run_as_root
check_rpi

if [ "${1}" == "-C" ] || [ "${1}" == "--clear" ]; then
    CLEAR_DMESG=1
fi

case "$(wfx_bus --show)" in
    spi)
        ;;
    sdio)
        IS_SDIO=1
        ;;
    *)
        exit 1
        ;;
esac

set -e
modprobe -v wfx -r
# With SDIO bus, chip have to be reset by SDIO host (while SPI slave can reset itself)
[ "$IS_SDIO" ] && echo 3f300000.mmc > /sys/bus/platform/drivers/mmc-bcm2835/unbind
[ "$CLEAR_DMESG" ] && dmesg -C
[ "$IS_SDIO" ] && echo 3f300000.mmc > /sys/bus/platform/drivers/mmc-bcm2835/bind
modprobe -v wfx
check_interface wlan0
echo "Success"
