#!/bin/bash
# Copyright (c) 2018, Silicon Laboratories
# See license terms contained in COPYING file

set -e
. wfx_set_env
run_as_root
check_rpi

USAGE="Usage: $(basename $0) OPTION

Show or set bus mode (SPI or SDIO)

Options:
  --help                 display this message
  --show                 show bus mode
  --set sdio|spi|spidev  set bus mode

Note: spidev is to be used only by Silabs teams for tests, this mode
requires specific firmware.
"

main()
{
    case "$1" in
        --help)
            echo "$USAGE"
            exit 0
            ;;
        --show)
            bus_show
            ;;
        --set)
            bus_set $2
            ;;
        *)
            echo "ERROR: unknown command $1" >&2
            echo "$USAGE" >&2
            exit 1
            ;;
    esac
}

bus_show()
{
    COUNT=0
    for OVERLAY in $(grep "^dtoverlay=" /boot/config.txt); do
        case "$OVERLAY" in
            *wfx-sdio*) MODE=sdio;   ((++COUNT)) ;;
            *wfx-spi*)  MODE=spi;    ((++COUNT)) ;;
            *spidev*)   MODE=spidev; ((++COUNT)) ;;
        esac
    done
    if [ "$COUNT" != "1" ]; then
        echo "ERROR: there is not exactly one bus selected" >&2
        exit 1
    fi
    echo "$MODE"
}

bus_set()
{
    MODE=$1
    case "$MODE" in
        sdio)   DRIVER=wfx-sdio ;;
        spi)    DRIVER=wfx-spi ;;
        spidev) DRIVER=spidev ;;
        *) echo "ERROR: unsupported bus mode: $MODE" >&2 && exit 1 ;;
    esac

    disable_line /boot/config.txt 'dtoverlay=wfx-'
    disable_line /boot/config.txt 'dtoverlay=spidev'
    enable_line /boot/config.txt "dtoverlay=$DRIVER"

    if [ "$DRIVER" = "wfx-spi" ]; then
        PI_VER=$(sed -nre 's/Raspberry Pi ?(.).*/\1/p' /proc/device-tree/model)
        if [ "$PI_VER" = "4" ]; then
            echo "WARNING: Raspberry Pi 4 detected, please be sure to use a SPI frequency of 25MHz"
            echo "manually check/edit dtoverlay=wfx-spi... in /boot/config.txt"
        fi
    fi

    echo "WARNING: reboot the board for the bus change to take effect (sudo reboot)"
}

main $@
