#!/bin/bash
# Copyright (c) 2018, Silicon Laboratories
# See license terms contained in COPYING file

PDS=/lib/firmware/wf200.pds

if ! [ -e $PDS ]; then
    echo "$PDS was not found" >&2
    exit 1
fi
realpath $PDS
