#!/bin/bash
# Copyright (c) 2018, Silicon Laboratories
# See license terms contained in COPYING file

. wfx_set_env
check_root

DEFAULT_CHIP_KEY=C0

if [ ! -d "$GITHUB_FIRMWARE_PATH" ]; then
    echo "Cannot find directory $GITHUB_FIRMWARE_PATH" >&2
    exit 1
fi

if [ $# -gt 0 ]; then
    if ! git -C $GITHUB_FIRMWARE_PATH checkout $1; then
        echo "Cannot get tag $1" >&2
        echo "Possible tags:"
        git -C $GITHUB_FIRMWARE_PATH tag | sed 's/^/  /'
        exit 1
    fi
fi

FIRMWARE_VER=$(git -C $GITHUB_FIRMWARE_PATH describe --tags --dirty)

printf "Installing firmware %s\n" "$FIRMWARE_VER"
for i in $GITHUB_FIRMWARE_PATH/wfm_wf200_??.sec; do
    INFILE=$i
    INFILE_BASE=$(basename $INFILE)
    OUTFILE_BASE=${INFILE_BASE%.sec}-$FIRMWARE_VER.sec
    OUTFILE=/lib/firmware/$OUTFILE_BASE
    set -ex
    cp $INFILE $OUTFILE
    ln -sfn $OUTFILE_BASE /lib/firmware/$INFILE_BASE
    set +ex
done

set -ex
ln -sfn wfm_wf200_$DEFAULT_CHIP_KEY.sec /lib/firmware/wfm_wf200.sec
set +ex
