#!/bin/bash

. wfx_set_env

FW_FILE="wfm_wf200.sec"
FW_GREP="wfm_wf200_"
LAST_FW=""
CURRENT_FW_TAG=""

if [ -f /lib/firmware/${FW_FILE} ];
then
	FW=$( ls /lib/firmware/${FW_FILE}  )
else
	FW=""
fi

if [ "${FW}" == "" ]; then
	if [ "${1}" != "quiet" ]; then
		echo "no FW loaded"
	fi
else
	real_fw=$( realpath ${FW} )
	if [ -f ${real_fw} ]; then
		git_path_check=$( echo ${real_fw} | grep ${GIT_WFX_DIR} )
		if [ ! -z $git_path_check ]; then
			CURRENT_FW_TAG=$( git  -C ${GITHUB_FIRMWARE_PATH}/ describe --exact-match --tags )
			if [ "${1}" != "quiet" ]; then
				echo "${FW} -> ${real_fw}  (from git tag ${CURRENT_FW_TAG})"
			fi
		else
			if [ "${1}" != "quiet" ]; then
				echo "${FW} -> ${real_fw} "
			fi
		fi
	else
		if [ "${1}" != "quiet" ]; then
			echo "ERROR: ${FW} is pointing at ${real_fw}, which doesn't exist!. Use 'wfx_use_firmware' to select a valid firmware"
		fi
	fi
	loaded_FWS=$( dmesg | grep ${FW_DMESG_GREP} )
	for loaded_fw in "${loaded_FWS}"
	do
		LOADED_FW=${loaded_fw}
	done
	if [ "${1}" != "quiet" ]; then
		if [ "${LOADED_FW}" == "" ]; then
			echo "Firmware is not loaded. Use 'wfx_reload' to load it"
		else
			echo "Last loaded firmware: ${LOADED_FW}"
		fi
	fi
fi
