#!/bin/bash
# Copyright (c) 2018, Silicon Laboratories
# See COPYING for license.

INSTALLED_FILE="$(realpath /lib/firmware/wfm_wf200.sec)"
LOADED_VER=$(dmesg | sed -nre 's/.*Firmware "(.*)".*/\1/p' -e 's/.*Label. \[(.*)\].*/\1/p' | tail -n 1)
printf "%-20s%s\n" "Installed file: "    "${INSTALLED_FILE:-not found}"
printf "%-20s%s\n" "Loaded version: "    "${LOADED_VER:-not found}"
