#!/bin/bash -ex

# Start a demo in access point mode with a local web server

. wfx_set_env
check_root

INTERFACE="wlan0"
ADDRESS="192.168.51.1/24"
DNSMASQ_CONF=$GITHUB_CONF_PATH/dnsmasq.conf
HOSTAPD_CONF=$GITHUB_CONF_PATH/hostapd.conf

check_interface "$INTERFACE"

# Ensure that all processes from a previous run are stopped
wfx_demo_stop

# Tell dhcpcd to release WLAN interface
dhcpcd --release "$INTERFACE"

# Set static IP configuration
ip addr flush dev "$INTERFACE"
ip addr add "$ADDRESS" dev "$INTERFACE"
ip link set "$INTERFACE" up

# Start DHCP server
dnsmasq -C "$DNSMASQ_CONF"

# Start hostapd
hostapd -B "$HOSTAPD_CONF"

# TODO: start HTTP server with a static page

# To allow traffic forwarding to a gateway, uncomment the following lines
#echo 1 > /proc/sys/net/ipv4/ip_forward
#iptables -t nat -A POSTROUTING -o eth0 -j MASQUERADE
