#!/bin/bash -e

# Start a demo in station mode for browsing

set -e
. wfx_set_env
check_root

INTERFACE="wlan0"
WPA_SUPPLICANT_CONF=$GITHUB_CONF_PATH/wpa_supplicant.conf
LIGHTTPD_CONF=$GITHUB_CONF_PATH/lighttpd.conf

check_interface "$INTERFACE"

# Ensure that all processes from a previous run are stopped
wfx_demo_stop

set -x

# Tell dhcpcd to control WLAN interface (in case of previous demo_AP)
ip addr flush dev "$INTERFACE"
dhcpcd --rebind "$INTERFACE"

# Start wpa_supplicant
wpa_supplicant -i "$INTERFACE" -c "$WPA_SUPPLICANT_CONF" -B -s

# Start web server
lighttpd -f "$LIGHTTPD_CONF"

# Start wpa_gui
if [ "$DISPLAY" != '' ]; then
    sudo -u pi wpa_gui & disown
else
    echo "ERROR: wpa_gui needs a display" >&2
    exit 1
fi
echo "Success"
