#!/bin/bash
# Copyright (c) 2018, Silicon Laboratories
# See license terms contained in COPYING file

# Start a demo in station mode for browsing

set -e
. wfx_set_env
check_root

INTERFACE="wlan0"
WPA_SUPPLICANT_CONF=$GITHUB_CONF_PATH/wpa_supplicant.conf
LIGHTTPD_CONF=$GITHUB_CONF_PATH/lighttpd.conf

check_interface "$INTERFACE"

# Ensure that all processes from a previous run are stopped
wfx_demo_stop

set -x

# Tell dhcpcd to control WLAN interface (in case of previous demo_AP)
ip addr flush dev "$INTERFACE"
dhcpcd --rebind "$INTERFACE"

# Start wpa_supplicant
wpa_supplicant -i "$INTERFACE" -c "$WPA_SUPPLICANT_CONF" -B -s

# Start web server
lighttpd -f "$LIGHTTPD_CONF"

if [[ $# -gt 0 ]]; then
    (
        # Configure wpa_supplicant manually
        wpa_cli flush
        wpa_cli add_network
        wpa_cli set_network 0 ssid \"$1\"
        if [[ $# -gt 1 ]]; then
            wpa_cli set_network 0 psk \"$2\"
            wpa_cli set_network 0 key_mgmt WPA-PSK
        else
            wpa_cli set_network 0 key_mgmt NONE
        fi
        wpa_cli enable_network 0
        wpa_cli select_network 0
    ) | grep FAIL && exit 1 || true
else
    # Configure wpa_supplicant using wpa_gui
    if [[ -n "$DISPLAY" ]]; then
        sudo -u pi wpa_gui & disown
    else
        echo "ERROR: no config provided and wpa_gui needs a display" >&2
        exit 1
    fi
fi
echo "Success"
