#!/bin/bash -ex

# Start a demo in station mode for browsing

. wfx_set_env
check_root

INTERFACE="wlan0"
WPA_SUPPLICANT_CONF=$GITHUB_TOOLS_PATH/demos/conf/wpa_supplicant.conf

# Check wlan0
if ! ip link show "$INTERFACE" &> /dev/null; then
    echo "Interface $INTERFACE not detected, exiting" >&2
    exit 1
fi

# Ensure that all processes from a previous run are stopped
wfx_demo_stop

# Tell dhcpcd to control WLAN interface (in case of previous demo_AP)
ip addr flush dev "$INTERFACE"
dhcpcd --rebind "$INTERFACE"

# Start wpa_supplicant
wpa_supplicant -i "$INTERFACE" -c "$WPA_SUPPLICANT_CONF" -B -s

# Start wpa_gui
if [ "$DISPLAY" != '' ]; then
    sudo -u pi wpa_gui & disown
else
    echo "wpa_gui needs a display" >&2
    exit 1
fi
