#!/bin/bash

. wfx_set_env
check_root

# 'wfx-wlan-spi' is for compatibility with early drivers. obsolete as from DRV-1.3.0
sed -i~ 's/^#dtoverlay=wfx-wlan-spi/dtoverlay=wfx-wlan-spi/m' /boot/config.txt
sed -i~ 's/^#dtoverlay=wfx-spi/dtoverlay=wfx-spi/m' /boot/config.txt
