#!/bin/bash

. wfx_colors

for f in "$@"; do
    if [ -e "$f" ]; then
        printf "───────────────────   %-40s\n" "$(realpath $f)"
        grep -v -e '^#' -e '^$' $1
    else
        printf "───────────────────   %-40s ${INV}NO_SUCH_FILE${NO}\n" "$f"
    fi
done
