#!/bin/bash

. wfx_set_env
check_root

# 'wfx-wlan-spi' is for compatibility with early drivers. obsolete as from DRV-1.3.0
sed -i~ 's/^dtoverlay=wfx-wlan-sdio/#dtoverlay=wfx-wlan-sdio/m' /boot/config.txt
sed -i~ 's/^dtoverlay=wfx-sdio/#dtoverlay=wfx-sdio/m' /boot/config.txt
