#!/bin/bash

. wfx_set_env
check_root
check_rpi

modprobe -v wfx -r

echo 3f300000.mmc > /sys/bus/platform/drivers/mmc-bcm2835/unbind

if [ "${1}" == "clear" ]; then
	dmesg -C
fi

echo 3f300000.mmc > /sys/bus/platform/drivers/mmc-bcm2835/bind

modprobe -v wfx
