#!/bin/bash
# Copyright (c) 2018, Silicon Laboratories
# See COPYING for license.

. wfx_set_env
check_root

set -ex
modprobe -v wfx -r

if [ "${1}" == "-C" ] || [ "${1}" == "--clear" ]; then
    dmesg -C
fi

modprobe -v wfx
set +ex
