#!/bin/bash

. wfx_set_env
check_root

modprobe -v wfx -r

if [ ${model} == "Pi" ]; then
	echo 3f300000.mmc > /sys/bus/platform/drivers/mmc-bcm2835/unbind
fi

if [ "${1}" == "clear" ]; then
	dmesg -C
fi

if [ ${model} == "Pi" ]; then
	echo 3f300000.mmc > /sys/bus/platform/drivers/mmc-bcm2835/bind
fi

modprobe -v wfx
