#!/bin/bash
# Copyright (c) 2019, Silicon Laboratories
# See license terms contained in COPYING file
#
# wfx_hif_send_msg sends a request payload (received as a text string)
# to the firmware via the debugfs 'wfx/send_hif_msg' file,
# and retrieve the confirmation message's status code (0 means 'SUCCESS')

# Filling HIF_INPUT with proper PHY number
PHY=$(iw dev | grep phy | sed -e 's/#//')
HIF_INPUT=$(ls /sys/kernel/debug/ieee80211/${PHY}/wfx/send_hif_msg)

#set -ex

# Opening file descriptor # 3 for reading and writing
# NB: We can't use sub processes to write/read (such as 'res=$(...)')
#  because these would lose the file descriptor
# Writing and reading from this file MUST be done in the same process
exec 3<>${HIF_INPUT}

# Write to file descriptor # 3 (using tee to avoid having hex data interpreted by echo)
echo -en "${1}" | tee >&3

# Read from file descriptor and copy to temporary file
#  (dd hex result can't be retrieved directly)
#  route dd messages (sent to stderr) to /dev/null to avoid cluttering the traces
dd count=1 <&3 > /tmp/hif_res 2> /dev/null

# Retrieve HIF result: first 16 bits of confirmation message (2nd item on hexdump 1st line)
status=0x$(hexdump /tmp/hif_res | grep ^0000000 | awk '{split($0,a," "); print a[2]}')

# close fd # 3
exec 3>&-

# return status
echo $((${status}))
exit 0
